packages/cli/PRIVACY.md
As proposed by legal team.
https://coveord.atlassian.net/browse/CDX-130
=> docs(analytics): change to privacy disclaimer

.deployment.config.json
Commit link rerefence: https://github.com/coveo/cli/commit/591040c6568cce03b031c3059cd4d4de87de8d7c
https://coveord.atlassian.net/browse/CDX-137
=> ci(rollout): configure initial changeset for rollout

.prettierignore
Ignore CHANGELOG.md files and README.md from the CLI 'cause it's generated.
=> chore(cli) create prettierignore file

.deployment.config.json
Will do a "deploy" in all environment: essentially, to terraform deploy in qa and prod (oauth client)
https://coveord.atlassian.net/browse/CDX-147
=> chore(deployment): modify deployment config for all env

.vscode/launch.json, packages/cli-e2e/entrypoints/common.js, packages/cli-e2e/entrypoints/entry.js, packages/cli-e2e/entrypoints/vsCodeExit.js, packages/cli-e2e/entrypoints/vscodeEntry.js, packages/cli-e2e/package.json
- Refactor JavaScript entrypoints
- Clean Doom references
https://coveord.atlassian.net/browse/CDX-119
=> chore(e2e): clean test end-to-end setup

packages/vue-cli-plugin-typescript/generator/template/src/EngineService.ts, packages/vue-cli-plugin-typescript/generator/template/src/router/index.ts
https://coveord.atlassian.net/browse/CDX-156
=> fix(vue): remove environment variables type warning

packages/angular/src/ng-add-setup-project/index_spec.ts, packages/angular/src/schema.json, packages/angular/src/schema.ts, packages/angular/src/search-token-server/files/.env.template, packages/angular/src/search-token-server/index_spec.ts
https://coveord.atlassian.net/browse/CDX-159
=> fix(angular): add missing user flag in Angular schematic

packages/angular/src/ng-add-setup-project/files/src/app/facet/facet.component.ts, packages/angular/src/ng-add-setup-project/files/src/app/pager/pager.component.ts, packages/angular/src/ng-add-setup-project/files/src/app/query-summary/query-summary.component.ts, packages/angular/src/ng-add-setup-project/files/src/app/result-list/result-list.component.ts, packages/angular/src/ng-add-setup-project/files/src/app/search-box/search-box.component.ts, packages/angular/src/ng-add-setup-project/files/src/app/sort/sort.component.ts
Another option would be to turn off strict type checking on the project creation...
https://coveord.atlassian.net/browse/CDX-101
=> fix(angular): add definite assignment assertion to props

packages/cli-e2e/utils/login.ts
=> test(cli): fix waitforloginpage

packages/angular/scripts/setup.js
https://coveord.atlassian.net/browse/CDX-163
=> fix(angular): copy schema only once in postbuild script

.github/workflows/build-binaries.yml
See [here](https://docs.github.com/en/actions/reference/environment-variables#determining-when-to-use-default-environment-variables-or-contexts)
CDX-165
=> fix(ci): replace github.ref by GITHUB_REF

.deployment.config.json
https://coveord.atlassian.net/browse/CDX-148
=> ci(cli): modify dep config to include snyk certifier

.github/workflows/build-binaries.yml
https://coveord.atlassian.net/browse/CDX-169
=> build(githubactions): add workflow_dispatch for build binaries

.github/workflows/build-binaries.yml, packages/cra-template/template.json, packages/cra-template/template/src/common/engineContext.ts
https://coveord.atlassian.net/browse/CDX-170
=> fix(react): add missing file & dependencies in React project

packages/angular/.gitignore, packages/angular/src/search-token-server/files/scripts/start-server.js
When I created the initial version of the schematic, it was outputing compiled JS files directly into the src folder. I updated the output folder but forgot to update the .gitignore.
https://coveord.atlassian.net/browse/CDX-168
=> fix(angular): add missing file to angular project

.github/workflows/build-binaries.yml, package-lock.json, package.json, scripts/get-tag.js
=> ci(githubactions): improve tag acquisition on build binaries

.github/workflows/build-binaries.yml
https://coveord.atlassian.net/browse/CDX-174
=> ci(githubactions): add env for credentials

packages/angular/src/common-rules/dependencies.ts, packages/angular/src/ng-add-setup-project/index.ts, packages/angular/src/ng-add/index.ts
https://coveord.atlassian.net/browse/CDX-164
=> fix(angular): `npm start` command on Angular project returns warning

packages/vue-cli-plugin-typescript/generator/template/src/components/Hero.vue
https://coveord.atlassian.net/browse/CDX-178
=> feat(vue): improve hero banner documentation link

packages/cli/package.json, packages/cli/src/commands/ui/create/angular.ts, packages/cli/src/commands/ui/create/react.ts, packages/cli/src/commands/ui/create/vue.ts, packages/cli/src/lib/utils/misc.ts
https://coveord.atlassian.net/browse/CDX-188
=> feat(cli): add --version flag for all `ui:create:*` commands

packages/cli/src/commands/ui/create/angular.ts
https://coveord.atlassian.net/browse/CDX-206
=> feat(angular): better feedback message on command completion 

packages/angular/src/ng-add-setup-project/files/src/app/hero/hero.component.html
https://coveord.atlassian.net/browse/CDX-207
=> fix(angular): fix headless doc links

packages/cli/src/lib/platform/environment.spec.ts, packages/cli/src/lib/platform/environment.ts
https://coveord.atlassian.net/browse/CDX-218
=> test(cli): complete UT for platform environment

packages/cli/src/hooks/prerun/prerun.spec.ts
https://coveord.atlassian.net/browse/CDX-217
=> test(prerun): add UT for prerun hook

packages/angular/src/search-token-server/files/server/.gitignore.template
https://coveord.atlassian.net/browse/CDX-184
=> feat(angular): ignore node_modules from server folder

packages/vue-cli-plugin-typescript/generator/index.js
https://coveord.atlassian.net/browse/CDX-222
=> feat(vue): support `npm run serve` command

.github/workflows/release.yml
https://coveord.atlassian.net/browse/CDX-240
=> ci(release): add manual version override

lerna.json
See:
-  https://github.com/lerna/lerna/tree/main/commands/version#--message-msg
- https://coveord.atlassian.net/wiki/spaces/CM/pages/1786708612/Package+Rollout+Certifier#PackageRolloutCertifier-Changesetsvalidationrules
Tested locally, it works.
---
https://coveord.atlassian.net/browse/CDX-244
=> ci(lerna): format release commit to be semantic and compatible with CD

.github/workflows/release.yml
https://coveord.atlassian.net/browse/CDX-251
=> ci(release): typo in create release github

packages/vue-cli-plugin-typescript/generator/template/src/components/Pager.vue
It causes errors in the console even if the app is working
https://coveord.atlassian.net/browse/CDX-250
=> fix(vue): fix typo in pager component

package.json
Should only run here https://github.com/coveo/cli/blob/master/packages/cli/package.json#L104-L105
---
https://coveord.atlassian.net/browse/CDX-257
=> ci(prepack): don't run oclif-dev cmd on root

.github/workflows/release.yml
See: https://github.com/lerna/lerna/issues/2404#issuecomment-571291441
https://coveord.atlassian.net/browse/CDX-260
=> ci(npm): put the token in the right place

packages/cli-e2e/package.json
https://github.com/lerna/lerna/tree/main/commands/publish#publishconfigaccess
----
https://coveord.atlassian.net/browse/CDX-261
=> ci(cli): no publish

.github/workflows/release.yml
https://coveord.atlassian.net/browse/CDX-265
=> ci(release): should prefix version with a v

README.md, packages/cli/README.md
Je trouvais que le readme principal manquait un peu de viande, alors j'en ai ajouté.
=> doc(cli): readme-review

terraform/.tgf.config
Manual TGF upgrade
--- 
[CA-67](https://coveord.atlassian.net/browse/CA-67)
=> Upgrade TGF to 3.13

.deployment.config.json
=> build(cli): add veracode configuration

.github/pull_request_template.md
Fixed the checkbox
-----
CDX-289
=> doc(pr): update pull request template

packages/cli-e2e/utils/terminal/terminal.ts, packages/cli-e2e/utils/timeStamper.ts
Same as #205, but with a Transform Stream & using Date localization options.
---
CDX-300
=> test(cli): add timestamps in log files (stream version)

.github/workflows/release.yml, packages/angular/package.json, packages/cli/package.json, packages/cra-template/package.json, packages/search-token-server/package.json, packages/vue-cli-plugin-typescript/package.json
Lerna was resetting the package.json before we commit, which is not what we want at all.
- Band-aid: put back the proper version
- Tell lerna to just no do that.
-----
CDX-328
=> fix(cli): set dependency and cd fix

packages/angular/src/ng-add-setup-project/rules/start.ts, packages/angular/src/search-token-server/files/scripts/port-allocator.mjs, packages/cra-template/template.json, packages/cra-template/template/scripts/port-allocator.mjs, packages/vue-cli-plugin-typescript/generator/index.js, packages/vue-cli-plugin-typescript/generator/template/scripts/port-allocator.mjs
Some async functions were not awaited properly, which I think cause some (rare) issues in the tests, and possibly to our users. (i.e. code is not executed and the code after assume it is, oups).
Also, small QoL improvement (imho), I migrated the code from CommonJS modules to ECMA ones, which are I think a bit cleaner (I do prefer the import syntax over the require 😅 )
E2E, although it's a race condition so... Tough to 'reliably' test. It should eliminate the issue listed in the Jira tho.
-----
CDX-398
=> fix(ui): use await/async

packages/cli/src/lib/platform/environment.ts
Extracted the fuss out of the method to make it cleaner.
- ❌  Manual Tests: above is enough imo ('specially the UT)
-----
CDX-404
=> refactor(cli): cleanup platformUrl method

.github/workflows/build-binaries.yml, .github/workflows/build.yml
https://coveord.atlassian.net/browse/CDX-186
This PR modifies the release process to ensure that the Windows executables are certified.
- ❌ Unit Tests: not possible
- ❌  Functional Tests: not possible
-----
CDX-186
=> build(cert): Sign Windows Executable

package-lock.json, package.json
This reverts commit 9ffbafb5a83214dd58a7c7b26700c4fb342748e3.
https://coveord.atlassian.net/browse/CDX-414
=> Revert "fix(J:CDX-227): bump @actions/github from 4.0.0 to 5.0.0 (#294)"

.github/workflows/build-binaries.yml
https://coveord.atlassian.net/browse/CDX-415
=> build: revert windows signing

.github/dependabot.yml, .github/workflows/codeql-analysis.yml, packages/cli-e2e/package-lock.json, packages/cli-e2e/package.json, packages/cli-e2e/utils/browserConsoleInterceptor.ts, packages/cli-e2e/utils/filelogger.ts, packages/cli-e2e/utils/server.ts, packages/cli-e2e/utils/terminal/action.ts, packages/cli-e2e/utils/terminal/do.ts, packages/cli-e2e/utils/terminal/on.ts, packages/cli-e2e/utils/terminal/orchestrator.ts, packages/cli-e2e/utils/terminal/terminal.ts, packages/cli-e2e/utils/terminal/when.ts, packages/cli-e2e/utils/timeStamper.ts, packages/cli/.eslintignore, packages/cli/.prettierignore, packages/cli/src/lib/base.ts, packages/cli/src/lib/config/config.ts, packages/cli/src/lib/decorators/preconditions/testsUtils/utils.ts, packages/cli/src/lib/oauth/oauth.ts, packages/cli/src/lib/platform/authenticatedClient.spec.ts, packages/cli/src/lib/platform/authenticatedClient.ts
I had lint errors on my PR CDX-87 and I did not want to include the file linting in the PR scope.
CDX-406
=> chore: lint E2E files

package-lock.json, package.json, scripts/get-tag.js, scripts/github-client.js
https://coveord.atlassian.net/browse/CDX-417
Upgrade dependency github actions.
Ran scripts locally
=> ci(github): upgrade @actions/github to 5.x

packages/cli/src/commands/org/config/monitor.ts, packages/cli/src/commands/org/config/preview.ts, packages/cli/src/commands/org/config/push.ts
Add missing analytics hooks for the various orgconfig commands
https://coveord.atlassian.net/browse/CDX-455
=> feat(analytics): add analytics hook on org:config commands

packages/cli/README.md, packages/cli/src/commands/source/push/new.spec.ts, packages/cli/src/commands/source/push/new.ts
https://coveord.atlassian.net/browse/CDX-457
Add new command to create a new PUSH source type.
https://coveord.atlassian.net/browse/CDX-457
=> feat(push): add push source create new command

packages/cli/README.md, packages/cli/src/commands/source/push/list.spec.ts, packages/cli/src/commands/source/push/list.ts
Add a command that list the available push source in your organization. Will be needed for upcoming command that allows to push local files from disk, since you need to specify which source to use.
-----
https://coveord.atlassian.net/browse/CDX-453
=> feat(push): add push source list command

packages/cli/README.md, packages/cli/jest.config.js, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/source/push/delete.spec.ts, packages/cli/src/commands/source/push/delete.ts
https://coveord.atlassian.net/browse/CDX-461
Add command that allows to delete document in a push source, using either a list of document URI, or olderThan pattern.
=> feat(push): add delete document push source command

packages/cli/src/commands/source/push/delete.spec.ts, packages/cli/src/commands/source/push/delete.ts
https://coveord.atlassian.net/browse/CDX-466
Applying documentation change request.
=> docs(push): documentation change on source:push:delete

.github/workflows/renovate-config-validator.yml, renovate.json
- Fixed the typo in the JSON (that is what I get for editing JSON in GitHub directly)
- Added a workflow check it only runs when renovate.json is modified ;)
- Added the validator
-----
CDX-479
=> chore(renovate): fix config and add validator

packages/cli/src/commands/source/push/add.ts
Add documentation link on source:push:add command.
https://coveord.atlassian.net/browse/CDX-480
=> docs(push): add link to github wiki

.github/workflows/release.yml
https://coveord.atlassian.net/browse/CDX-489
Linked to https://github.com/lerna/lerna/issues/2788
=> ci(npm): add no verify access for usage with automation token

packages/cli/package.json
https://coveord.atlassian.net/browse/CDX-490
Some "nice to have" when listing all topics
=> docs(push): add topic documentation for source

packages/cli/README.md, packages/cli/src/commands/org/config/list.spec.ts, packages/cli/src/commands/org/config/list.ts, packages/cli/src/commands/org/config/pull.ts
https://coveord.atlassian.net/browse/CDX-498
Add a `org:config:list` command.
It can be used in conjunction/in tandem with `org:config:pull` which accept a snapshot id as a flag.
https://coveord.atlassian.net/browse/CDX-498
=> feat(config): add list snapshot command

packages/cli/src/commands/org/config/list.spec.ts, packages/cli/src/commands/ui/create/angular.spec.ts, packages/cli/src/commands/ui/create/react.spec.ts, packages/cli/src/commands/ui/create/vue.spec.ts, packages/cli/src/hooks/analytics/analytics.spec.ts, packages/cli/src/lib/config/config.spec.ts, packages/cli/src/lib/config/config.ts
Switch to the synchronous pathExists, fix the side-effects that were putting the UT red.
Second clean-up round put aside in CDX-515
=> remove last asynchronicity

packages/cli-e2e/__tests__/orgConfig.specs.ts, packages/cli/src/lib/decorators/preconditions/git.ts
git is a .exe on windows, not a .cmd
- Will be done in subsequent Jira
<!-- For Coveo Employees only. Fill and uncomment this section.
-----
CDX-516
=> fix: remove `appendCmdIfWindows`

packages/cli-e2e/utils/login.ts
Hypothesis: We try to click on the button while the JavaScript ain't fully loaded yet.
Proposed fix: Wait for everything to load (hopefully)
FT/CI
-----
CDX-488
=> test(e2e): waitForNavigation will logging-in

packages/cli-e2e/utils/login.ts
Same as #390. Just did a bad merge (not semantic)
CDX-488
=> fix(e2e): waitForNavigation on login

packages/cli/src/commands/org/config/preview.ts, packages/cli/src/commands/org/config/push.ts, packages/cli/src/lib/snapshot/reportViewer/reportViewer.ts, packages/cli/src/lib/snapshot/snapshot.ts
https://coveord.atlassian.net/browse/CDX-525
Removing a bunch of old TODOs.
-----
CDX-525
=> chore: remove old TODOs

LICENSE
See https://github.com/coveo/cli/blob/master/LICENSE#L178-L187
=> doc(license): add licensor info

.github/workflows/merge-bot.yml
Add a bot that manages PR merging in place of the user.
Tried at https://github.com/louis-bompart/vigilant-journey/pull/23
GitHub repo of the bot: https://github.com/coveo/merge-bot
None yet 🤣 
-----
CDX-560
=> ci(pr): add merge bot

packages/cli/src/lib/snapshot/expandedPreviewer/expandedPreviewer.spec.ts
just some UT on top of yours E2E ;)
=> 626 additional uts

packages/create-atomic/templates/webpack.config.mjs
This allows compiling ts files other than index.ts
https://coveord.atlassian.net/browse/CDX-670
=> fix: resolve ts/js files for generated atomic project (webpack)

.deployment.config.json
Snyk fixed our issue, I tested locally and the devtooling team will update the certifier. But in the meantime, just to be sure it works 💯, let's try with that? (Tested on my machine, it works, but well, my machine ain't the CI/CD)
=> ci: target snyk-cli updated docker

scripts/get-release-artifact-and-commit-sha.js, scripts/get-tag.js, scripts/release-changelog.js
Fix missing refactor following the changes made on #574 
-----
CDX-719
=> ci(release): fix tag usage

packages/create-atomic/package.json
https://coveord.atlassian.net/browse/CDX-724
=> fix: specify templates/.gitignore in files

.deployment.config.json
=> ci: fix typo in deployment config path

renovate.json
=> chore(deps): lock npm to 8.4.x

.github/workflows/release.yml
I did some changes in Snyk for the PR checks to run with Yarn. This port the logic to the release workflow
=> chore(snyk): port snyk-master changes to release

.github/workflows/release.yml
=> chore(snyk): typo in config

.github/workflows/release.yml
=> chore(snyk): fix script path

packages/cli-e2e/utils/platform.ts, scripts/get-code-scanning-alerts.js
I forgot that `.filter` does not `.filter` in-array but creates a copy 🤦 .
So I changed the whole thing to be more readable.
=> chore(snyk): fix alert threshold script

.github/workflows/release.yml
=> chore(gh): typo

.github/workflows/release.yml, .gitignore, scripts/releaseV2/phase3-git-commit-tag-push.mjs
- Remove a horrible mistake.
- Prevent said horrible mistake to ever, ever, ever happen again. God damn.
- Fix missing import
=> chore(gh): fix missing import + npm publish token

scripts/releaseV2/utils/wait-for-published-packages.mjs
https://coveord.atlassian.net/browse/CDX-828
Replace require by import, rename file accordingly to its new nature (implict cjs to explicit mjs)
=> chore(gh): convert waitForPackage script from CJS to ESM

package-lock.json, package.json, scripts/releaseV2/phase3-git-commit-tag-push.mjs
Format commit so that it satisifies the 'version bump' condition for the package rollout certifier ([see Confluence](https://coveord.atlassian.net/wiki/spaces/CM/pages/1786708612/Package+Rollout+Certifier))
=> chore(pipeline): fix release commit message

renovate.json
Prevent fkill 7->8 update (CJS->ESM)
=> chore(renovate): lock fkill for e2e

packages/cli/src/hooks/prerun/prerun.spec.ts, packages/cli/src/hooks/prerun/prerun.ts
https://coveord.atlassian.net/browse/CDX-888
Do not prompt analytic message when running in a CI
=> fix: do not prompt on CI

.github/workflows/release.yml
https://coveord.atlassian.net/browse/CDX-903
Forgot a `ignore-script` for the CD stage w/ yarn.
=> chore(ci): do not run pip on CI

packages/atomic/create-atomic/package.json
https://coveord.atlassian.net/browse/CDX-764
Forgot to add a '..' in the path in PR #714, this fixes that (the template was already good because it was already at this depth level)
=> chore(cd): fix bad path for release script

JenkinsfileCloudfrontInvalidation
I _think_ that will fix the issue that occured with the JenkinsfileCloudfrontInvalidation, cannot really be sure tho.
=> chore(cd): ignore-scripts + update node

.github/workflows/build-binaries.yml, package-lock.json, package.json, scripts/get-commit-short-hash.mjs
Just check the 2 latest release, you'll see the change on the binary names. This PR reflects that
=> chore(cd): change binary name targeted for signing

package-lock.json, packages/cli/package.json, packages/cli/src/__stub__/batchUploadDocumentsFromFilesReturn.ts, packages/cli/src/commands/source/push/add.spec.ts, packages/cli/src/commands/source/push/add.ts, packages/cli/src/commands/source/push/delete.spec.ts, packages/cli/src/commands/source/push/delete.ts, packages/cli/src/lib/push/userFeedback.ts
https://coveord.atlassian.net/browse/CDX-922
Bump version of push-api-client to support Stream API (#749)
=> chore: bump push-api-client version

packages/cli-e2e/__tests__/orgResources.specs.ts, packages/cli/src/commands/org/resources/__snapshots__/monitor.spec.ts.snap, packages/cli/src/commands/org/resources/list.spec.ts, packages/cli/src/commands/org/resources/list.ts, packages/cli/src/commands/org/resources/monitor.spec.ts, packages/cli/src/commands/org/resources/monitor.ts, packages/cli/src/commands/org/resources/preview.spec.ts, packages/cli/src/commands/org/resources/preview.ts, packages/cli/src/commands/org/resources/pull.spec.ts, packages/cli/src/commands/org/resources/pull.ts, packages/cli/src/commands/org/resources/push.spec.ts, packages/cli/src/commands/org/resources/push.ts, packages/cli/src/lib/flags/snapshotCommonFlags.ts
https://coveord.atlassian.net/browse/CDX-944
Rename `--target`/`-t` to `--organization`/`-o`
`--target` and `-t` are removed. Considered OK because of the beta tag.
=> chore(snapshot): refactor -t to -o

packages/cra-template/template/src/index.tsx
- typescript says that document.getElementById('root') can be null
- [this asserts that it will never be null](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-)
=> fix: add null check override in CRA template

packages/cli/src/lib/snapshot/reportPreviewer/reportPreviewer.ts, packages/cli/src/lib/snapshot/snapshotConstant.ts
https://coveord.atlassian.net/browse/CDX-499
Simply copy pasted the translations from the adminUI.
=> feat: add snapshot type labels

.github/workflows/build.yml
Lock npm cli to 8.10.0.
Empirical fix, I did not pinpoint the issue exactly yet. I just know that npm@8.11.0 cause the issue. (see the builds).
I also tried bumping every Angular deps, no effect.
I'll be investigating the root cause in another Jira.
=> chore(npm): lock npm

packages/cli/src/commands/commerce/catalog/create.ts, packages/cli/src/commands/source/catalog/add.ts, packages/cli/src/lib/recipes/commerce/snapshot.json
Setting command for catalog creation.
Parsing the data and creating the catalog is the first step in the commerce recipe.
=> feat: setup the Catalog Command

packages/atomic/create-atomic/src/plopfile.ts
https://coveord.atlassian.net/browse/CDX-1016
Prompt was taking the default template. because validate wasn't called.
Should still pass
=> fix(create-atomic): download prompt selected hosted page

scripts/releaseV2/phase2-bump-all-packages.mjs
=> chore(cd): json stringify

package-lock.json, packages/angular/package.json, packages/atomic/template/package.json, scripts/releaseV2/phase2-bump-all-packages.mjs
https://coveord.atlassian.net/browse/CDX-1027
I forgot to initialize the accumulator with an array, meaning it defaulted with an empty string, which broke the algorithm. bigderp.
Ran in debug mode on verdaccio, looks alright, tho my confidence after so many failure ain't high.
=> chore(cd): fix reduce with actual accumulator

package-lock.json, packages/cli/package.json, packages/cli/src/commands/org/search/dump.spec.ts, packages/cli/src/commands/org/search/dump.ts
New algo:
1. Search until dry or `chunkSize` amount of results is in RAM.
2. Append all fields name found into an array that stay alive till the end of the process.
3. Dump the aggregatedResults into a file, clear aggregatedResults and replace it with the overhead if any.
4. Rince and repeat till out of results.
5. When done, transform the array of field names into a set and into an array again (ensure unicity) then convert all chunks file into CSV.
=> fix(dump): csv header should have all fields associated with the source

packages/cli/src/commands/org/resources/pull.spec.ts, packages/cli/src/commands/org/resources/pull.ts, packages/cli/src/lib/commonFormaters/index.ts
- Added a check to see if the snapshotId has been provided thru the flag.
- Refactors/code cleaning
=> fix(snapshot): do not delete snapshot when provided with the flag

packages/cli/src/commands/org/resources/preview.ts, packages/cli/src/commands/org/resources/pull.ts, packages/cli/src/commands/org/resources/push.ts, packages/cli/src/lib/flags/snapshotCommonFlags.ts, packages/cli/src/lib/snapshot/snapshotCommon.ts, packages/cli/src/lib/snapshot/vaultHandler.ts
https://coveord.atlassian.net/browse/CDX-1044
No code change. Only `TODOs` to tackle in other PRs
=> chore: san-check flag and argument consistency

README.md
https://coveord.atlassian.net/browse/CDX-1077
=> docs(m1): add download link for M1

package-lock.json, packages/atomic/create-atomic/scripts/packageTemplate.json, packages/atomic/template/README.md, packages/atomic/template/package.json, packages/atomic/template/stencil.config.ts, packages/cli-e2e/__tests__/__snapshots__/atomic.specs.linux.ts.snap, packages/cli-e2e/__tests__/__snapshots__/atomic.specs.windows.ts.snap
https://coveord.atlassian.net/browse/CDX-1098
There's 2 ways to deploy to netlify:
1. Link to a Github (& others) repo & enable continuous deployment
2. Do a manual deployement with `netlify deploy`
Basically the generated project did not work with 1)
None
We don't test netlify deployment
=> feat(create-atomic): replace variables for continious deployment

renovate.json
https://coveord.atlassian.net/browse/CDX-1103
Atomic typing on current latest are broken, so let's freeze it for now
=> chore: lock atomic

package-lock.json, packages/angular/project.json, packages/cli-e2e/__tests__/__snapshots__/atomic.specs.ts.snap, packages/cli-e2e/project.json, packages/cli/commons-dev/project.json, packages/cli/commons/.gitignore, packages/cli/commons/package.json, packages/cli/commons/project.json, packages/cli/commons/tsconfig.json, packages/cli/core/project.json, packages/cli/source/project.json, packages/cra-template/.npmignore, packages/cra-template/project.json, packages/search-token-lambda/.npmignore, packages/search-token-lambda/project.json, packages/search-token-server/.npmignore, packages/search-token-server/project.json, packages/vue-cli-plugin-typescript/.npmignore, packages/vue-cli-plugin-typescript/project.json
https://coveord.atlassian.net/browse/CDX-1124
The build process fails because it looks for 'commons' and 'commons-dev' and was not finding them.
This was caused because the project files were missing, or the name was missing.
This fix that by ensuring all project names are explicitly defined (so no more relying on nx for building the project name)
=> chore: add missing project.json

.github/workflows/release.yml, scripts/releaseV2/phase1-get-new-version.mjs
https://coveord.atlassian.net/browse/CDX-764
Add back the support for manual version, required to fix partial releases
=> chore: support input version

packages/cli/commons-dev/package.json, packages/cli/commons/package.json, packages/cli/source/package.json
- Add missing release:phase2 scripts
- Add missing publishConfig
- Remove readme generation for the plugin (will revisit after 1st release)
=> chore: fix package.json of new packages

.github/workflows/release.yml, package.json, packages/cli/commons-dev/.npmignore, packages/cli/commons/.npmignore, packages/cli/commons/package.json
Derp: I need DEBUG=*. It was equal to "true".
=> chore: add debug option on CI/CD

packages/cli/commons-dev/package.json, packages/cli/commons/package.json
Add some metadata, mainly license (snyk was whining cause of this)
=> chore: add license, author, description

.github/workflows/build.yml
Migration service is having an issue in stg. Don't want to freeze the build while waiting.
=> test: disable snapshot e2e

.github/workflows/delete-resources.yml
=> chore: disable week-end runs

packages/cli/core/package.json, packages/cli/core/src/commands/config/get.ts, packages/cli/core/src/commands/config/set.ts
https://coveord.atlassian.net/browse/CDX-1189
Examples, examples, examples.
=> docs(cli): improve config:* documentation

packages/cli/core/package.json, packages/cli/core/src/commands/org/resources/list.ts, packages/cli/core/src/commands/org/resources/monitor.ts, packages/cli/core/src/commands/org/resources/preview.ts, packages/cli/core/src/commands/org/resources/pull.ts, packages/cli/core/src/commands/org/resources/push.ts
https://coveord.atlassian.net/browse/CDX-1190
Examples, examples, examples.
=> docs(cli): improve org:resources:* documentation

packages/cli/core/src/commands/auth/__snapshots__/login.spec.ts.snap, packages/cli/core/src/commands/auth/login.spec.ts, packages/cli/core/src/commands/auth/login.ts
https://coveord.atlassian.net/browse/CDX-1191
Mention `coveo config:set -o` mostly
=> feat(cli): improve auth:login final feedback

packages/cli/core/src/commands/org/resources/__snapshots__/list.spec.ts.snap, packages/cli/core/src/commands/org/resources/list.spec.ts, packages/cli/core/src/commands/org/resources/list.ts
Flags related to List command are not applying when running the command.
=> fix: ensure flags are applied to `org:resources:list` command

Jenkinsfile, scripts/get-release-artifact-and-commit-sha.mjs, scripts/releaseV2/phase1-bump-all-packages.mjs
- Target the proper tag for the release download on Jenkins.
=> chore: fix release script

.github/workflows/release.yml
GitHub does some funky stuff for the checkout. This seems to fix it. 
Inspired by https://github.com/actions/checkout/issues/206#issuecomment-607496604
Before: https://github.com/coveo/cli/actions/runs/3252334483/jobs/5338428208
After: https://github.com/coveo/cli/actions/runs/3252358715/jobs/5338480219
=> chore(release): unshallow tags

package-lock.json, packages/cli-e2e/package.json
- In the releasepocalypse of last week, I didn't take into account this manual fix. This fix that.
=> chore(e2e): update @coveo/cli

.github/workflows/build.yml
CDX-1157
Enable back E2E tests for snapshots
=> test(snapshot): enable back e2e

packages/cli/core/src/lib/snapshot/vaultEntriesFunctions/transferFromOrganization.ts
I noticed a small typo as I was working on something else, so here's a quick fix 🙂
CDX-1219
=> docs(snapshot): add missing r to transfering

packages/cli/core/src/commands/org/resources/monitor.ts, packages/cli/core/src/commands/org/resources/pull.ts, packages/cli/core/src/commands/org/resources/push.ts
Add examples and their description
=> feat: add examples on `org:resources:*` commands

package-lock.json, packages/cli/core/package.json, packages/cli/source/package.json
https://coveord.atlassian.net/browse/CDX-227
Bump `@coveo/push-api-client` package
=> chore(deps): update push-api-client

.github/workflows/build.yml
Derp
[CDX-1223](https://coveord.atlassian.net/browse/CDX-1223)
=> chore(prerelease): generate missing topology

scripts/releaseV2/phase1-bump-all-packages.mjs
After publishing, we were using `npm show` to validate that the package was released properly... but we were doing so on the `latest` tag.
This cannot work when we work with `beta` tag.
So I changed that. And then I also DRY: `npm show` is essentially what `describeNpmTag` was doing: less code, less bug (maybe).
=> chore(prerelease): check beta tag and not latest on prerelease

packages/cli/core/README.md
Bodge the readme, for now, will investigate generation on another PR.
=> docs(cli): manual readme for now

packages/cli/core/README.md, packages/cli/core/package.json, packages/cli/core/scripts/post-readme.mjs
Add a script that modifies the readme after oclif.
=> fix(cli): fix readme generation

.github/workflows/delete-resources.yml, packages/cli-e2e/cleaning.ts, scripts/cleaning/delete-orgs.js
https://github.com/coveo/cli/pull/1043 in this one I use `ubuntu-20-04` and not `ubuntu-20.04` as test run id.
This fixes that.
=> chore(e2e): derp delete proper org name

scripts/github-client.js
To be clear, we don't need it for usual operations, it's working fine today. But my gut-feeling is that one day it may causes us trouble so let's bump it up
=> chore: ensure we got all assets

packages/cli-e2e/__tests__/__snapshots__/atomic.specs.ts.snap
Tested the result of the command still looks good.
Probably a change in the backend.
=> test(atomic): update snap

.github/actions/e2e-clean/action.yml, packages/cli-e2e/__tests__/__snapshots__/atomic.specs.ts.snap, scripts/cleaning/delete-orgs.js
We missed a change when updating the platform client, this address that.
CI/CD
=> chore(cleaning): fix org cleaning derp

packages/cli-e2e/__tests__/__snapshots__/atomic.specs.ts.snap, packages/cli-e2e/__tests__/atomic.specs.ts
Update the snap, steal the fix from #1074
=> test: update atomic snap

packages/cli/core/README.md
but more importantly, have some change in CLI so a release is done proper.
CDX-764
=> chore: clean readme

scripts/releaseV2/phase2-git-commit-tag-push.mjs
We update the `template.json` post npm install. Which is nice, but we forgot to ignore it for the QA gate.
This fix that
=> chore: in cd ignore also changes in template.json

renovate.json
Reduce the frequency to match other repos.
CDX-227
=> chore: change renovate update schedule

packages/ui/vue/create-headless-vue/template/README.md
=> fix(vue): bad key in generated readme

.github/workflows/renovate-jest-snap-updater.yml
My workflow is invalid because of this 🤦
=> chore: add missing version tag

package-lock.json, package.json, packages/cli-e2e/package.json, packages/cli/commons/package.json, packages/cli/core/package.json, packages/cli/source/package.json, packages/ui/atomic/create-atomic/package.json, packages/ui/search-token-lambda/package.json, packages/ui/search-token-server/package.json, packages/ui/vue/create-headless-vue/template/package.json
=> chore: update platform client

package-lock.json, packages/cli/commons/package.json
=> chore(cli-commons): install json schema as a cli commons dep

.github/workflows/renovate-jest-snap-updater.yml
https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability TIL
-------
[CDX-1328](https://coveord.atlassian.net/browse/CDX-1328)
=> chore: no env in jobs.<job_id>.name

.github/workflows/renovate-jest-snap-updater.yml
Need git ident to commit.
SO CLOSE! https://github.com/coveo/cli/actions/runs/4245890499/jobs/7381998582
=> chore: jest snap updater, add git ident

.github/workflows/renovate-jest-snap-updater.yml
- Add https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushautoSetupRemote
- Refactor git configuration into its own step
=> chore: jest snap updater

.github/workflows/renovate-jest-snap-updater.yml
CDX-1328
See #1123 , the PR_NUMBER is not evaluated.
=> chore: fix pr body of jest snap updater

Jenkinsfile, scripts/get-release-artifact-and-commit-sha.mjs
Git in recent version doesn't like when the one running a git cmd and the owner of the file differ.
This fix that and add some logs.
- THis branch has been used for the latest release.
=> chore(jenkins): fix git dubious ownership error in jenkins

rfcs/accepted/0001-cli-atomic-taxonomy.md
https://coveord.atlassian.net/browse/CDX-1358
------
[See the proposed file!](https://github.com/coveo/cli/blob/rfc/cli-taxonomy-v2/rfcs/0001-cli-atomic-taxonomy.md)
=> chore: propose new taxonomy for atomic commands

packages/ui/atomic/health-check/package.json
Add missing `prepublishOnly` script. Missing script for [CDX-1377](https://coveord.atlassian.net/browse/CDX-1377).
[CDX-1377]: https://coveord.atlassian.net/browse/CDX-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add missing prepublishOnly script

packages/cli-e2e/deploy-project/coveo.deploy.json, packages/cli/core/src/commands/ui/deploy.spec.ts, packages/cli/core/src/commands/ui/deploy.ts, packages/ui/atomic/template/coveo.deploy.json
Add a schemaVersion property, no validation for now (we only have one version after all)
=> fix(atomic): add schemaVersion for deploy.json

packages/ui/atomic/tempdoc/README.md
=> docs(atomic): update README.md

packages/cli/core/src/commands/ui/__snapshots__/deploy.spec.ts.snap, packages/cli/core/src/commands/ui/deploy.spec.ts, packages/cli/core/src/commands/ui/deploy.ts
- fix: await properly the update call.
- the rest of the 'fix' was done by the revamp of the error handling
- test: add a test case
=> fix(atomic): ensure error is properly printed

packages/ui/atomic/create-atomic-component/template/src/components/sample-component/stencil.config.ts, packages/ui/atomic/create-atomic-component/tests/__snapshots__/test.spec.ts.snap, packages/ui/atomic/create-atomic-result-component/template/src/components/sample-result-component/stencil.config.ts, packages/ui/atomic/create-atomic-result-component/tests/__snapshots__/test.spec.ts.snap
Readme file was generated and placed inside the `src/` folder... Which makes the health-check fails
=> fix: move readme one level higher 

package-lock.json, utils/release/git-lock.mjs
- lockfile syncing: otherwise, `git-lock` was not found
- add shebang: otherwise bash is confused.
=> chore: lockfile sync + shebang

.github/workflows/release.yml, package-lock.json, packages/cli/source/package.json, utils/release/git-lock.mjs, utils/release/git-publish-all.mjs, utils/release/package.json
Now with #1261, the bot has to overcome/bypass the checks. The way of doing it is using a Deploy Key.
This PR does that.
=> ci: use deploy key

.github/workflows/release.yml, utils/release/git-lock.mjs, utils/release/git-publish-all.mjs
We had duplicate instructions between the js files and the workflow. I think the JS is more readable. (i.e. logic is embedded in semantic-monorepo-tools)
=> ci: remove duplicate scripts

package-lock.json, package.json, packages/cli/source/package.json, utils/release/git-lock.mjs, utils/release/git-publish-all.mjs, utils/release/package.json
I manually completed release-13 by running the last git fetch command of the script + a git push force
Requires https://github.com/coveo/semantic-monorepo-tools/pull/149 and to modify our `gitPush` usage
=> ci: push the last `gitSetRefOnCommit` to remote

packages/cli/core/src/commands/atomic/component.ts, packages/cli/core/src/commands/atomic/init.ts
https://coveord.atlassian.net/browse/DOC-12589
I noticed that there weren't many details in a few commands, so here's a PR to try to add some meat on the bone 🙂 
No tests required. String changes only.
=> docs(cli): add details on commands related to custom components

packages/cli/core/src/commands/atomic/component.ts, packages/cli/core/src/commands/atomic/init.ts
Remove the beta tags of the commands
=> feat(atomic): remove beta tags

packages/ui/atomic/create-atomic-component/template/src/components/sample-component/src/sample-component.tsx, packages/ui/atomic/create-atomic-component/tests/__snapshots__/test.spec.ts.snap, packages/ui/atomic/health-check/src/e2e/__snapshots__/test.spec.ts.snap
The initializeBindings fail without the preliminary await
Tricky, I don't know how to do an automated test for that.
My test is:
- try use the HSP feature with a page component without this await, the page component should not initialize properly
- try use the HSP feature with a page component with this await, the page component should initialize properly
=> fix(atomic): wait for atomic to load/init on page component

packages/ui/atomic/create-atomic-component-project/package.json, packages/ui/atomic/create-atomic-component/package.json, packages/ui/atomic/create-atomic-result-component/package.json, packages/ui/atomic/health-check/package.json
Update some meta in the ACCD packages.
Will be merged with footer: 
`BREAKING CHANGE: Official release of the Atomic Custom Components Distribution Packages.`
No true breaking
=> feat(atomic)!: meta update + major bump

package-lock.json, packages/cli-e2e/__tests__/__snapshots__/atomic.specs.ts.snap, packages/ui/atomic/create-atomic-component-project/template/package.json, packages/ui/atomic/create-atomic-component-project/tests/__snapshots__/test.spec.ts.snap, packages/ui/atomic/create-atomic-component/template/src/components/sample-component/package.json, packages/ui/atomic/create-atomic-component/tests/__snapshots__/test.spec.ts.snap, packages/ui/atomic/create-atomic-result-component/template/src/components/sample-result-component/package.json, packages/ui/atomic/create-atomic-result-component/tests/__snapshots__/test.spec.ts.snap, packages/ui/atomic/health-check/package.json, packages/ui/atomic/health-check/src/e2e/__snapshots__/test.spec.ts.snap
`@types/jest` was the main culprit, added some cleaning/pinning as well
=> fix(accd): updates deps

rfcs/accepted/0002-cd-update-snap.md
=> ci: proposal - update Jest Snaps at release

packages/ui/atomic/create-atomic-component-project/template/src/pages/index.html, packages/ui/atomic/create-atomic-component-project/tests/__snapshots__/test.spec.ts.snap, packages/ui/atomic/create-atomic-component/tests/__snapshots__/test.spec.ts.snap, packages/ui/atomic/create-atomic-result-component/tests/__snapshots__/test.spec.ts.snap, packages/ui/atomic/health-check/src/e2e/__snapshots__/test.spec.ts.snap, packages/ui/atomic/template/src/pages/index.html.hbs, packages/ui/atomic/template/stencil.config.ts
https://coveord.atlassian.net/browse/CDX-1465
Allow imports by using `/headless` directly in the html files. This should allow users using functions from headless without too much hassle.
=> feat: support imports from `/headless`

packages/cli/core/src/lib/snapshot/expandedPreviewer/filesDiffProcessor.spec.ts, packages/cli/core/src/lib/snapshot/expandedPreviewer/filesDiffProcessor.ts
https://coveord.atlassian.net/browse/CDX-1481
Only perform detailed diff on JSON files.
=> fix: only diff json files

.github/workflows/release.yml
https://coveord.atlassian.net/browse/CDX-1497
=> ci(cli): fix release workflow

.github/workflows/release.yml
=> chore: missing v in binaries output

.github/workflows/release.yml
=> chore: use github_env

.github/workflows/release.yml
=> chore: fix release dl/up path

utils/release/git-publish-all.mjs
=> chore: ignore the snap dep pipeline kthx

.github/workflows/release.yml, package-lock.json, package.json, packages/cli/commons/package.json, packages/cli/core/package.json, packages/cli/source/package.json, packages/ui/angular/package.json, packages/ui/atomic/create-atomic-component-project/package.json, packages/ui/atomic/create-atomic-component/package.json, packages/ui/atomic/create-atomic-result-component/package.json, packages/ui/atomic/health-check/package.json, packages/ui/search-token-server/package.json, utils/release/create-github-release.mjs, utils/release/git-publish-all.mjs, utils/release/is-cli-release.mjs
- Add `npm test:ci:snap` to update non-e2e snap
- Update all snap during the release
- Fix the release
A lot of releases.
=> chore: stabilize release

utils/release/git-lock.mjs
This piece of code fails, we removed it UI-Kit side, let's do the same here (fix-it-twice maybe later: import the new nicer logic from UI-Kit)
=> chore: remove-git-lock

package-lock.json, package.json, utils/release/npm-publish-package.mjs, utils/release/package.json, utils/release/reify.mjs
The reification fails for some packages for obscure reasons (gut feeling, arborist bug).
Trying to do like coveo/ui-kit
=> take2, reify once, later

packages/cli-e2e/setup/utils/verdaccio.ts, packages/cli-e2e/verdaccio/config.yaml, utils/release/reify.mjs
=> chore: reify, use opt chaining where relevant

package.json
[CDX-764](https://coveord.atlassian.net/browse/CDX-764)
Force the build of the whole project before attempting the publication
[CDX-764]: https://coveord.atlassian.net/browse/CDX-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: force prebuild

package-lock.json, packages/ui/atomic/health-check/package.json
Manual bump mainly to have something changed since last release so that the process doesn't choke up
=> chore: update zod

README.md
=> chore: update readme link

packages/cli/core/src/lib/snapshot/snapshotReporter.ts
#1453 , I didn't test the suggestion, and it was breaking the code. Iterating from the OG code + suggestions, here's a nice solution.
- Reproduced reported issue w/ master and latest release
- Did not with this change
=> fix: resource type predicate

packages/cli/core/src/commands/org/resources/pull.ts
https://coveord.atlassian.net/browse/CDX-1592
Testing: Manual. Hard to test as its a corner case :/
=> fix(pull): default on resources user has access to

package-lock.json, package.json, packages/cli/commons/package.json, packages/cli/commons/src/platform/authenticatedClient.ts, packages/cli/core/package.json
Need to update platform-client to support new resource types CATALOG and CATALOG_CONFIG.
In new platform-client version, CreateApiKeyModel does not have `enabled` attribute.
I created a snapshot and applied it to another org with catalogs.
=> feat(resources): support catalogs in resource snapshots

.github/workflows/build.yml
https://coveord.atlassian.net/browse/CDX-1615
=> chore: use nvmrc

.github/workflows/release.yml
Update actions/download|upload-artifact to v4, as v3 is sunset
=> chore: update actions

.github/workflows/release.yml
Follow up of #1505 , forgot a couple places
=> chore: update actions again

utils/release/git-publish-all.mjs
CDX-764.
```js
''.split('\n')[0]==='' 
```
😮‍💨
=> chore: handle empty packageReleased
